"""Tests for PDF validation before KDP upload."""

import tempfile
from pathlib import Path

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from libro.common.pdf_utils import trim_size_pts
from libro.common.pdf_validation import (
    validate_cover,
    validate_interior,
    validate_pdf_structure,
)
from libro.branding.cover import CoverGenerator


def _make_pdf(path: Path, page_size: tuple, num_pages: int = 1) -> Path:
    """Helper: create a minimal PDF with given page size and count."""
    c = canvas.Canvas(str(path), pagesize=page_size)
    for _ in range(num_pages):
        c.drawString(72, 72, "test")
        c.showPage()
    c.save()
    return path


def test_validate_structure_valid_pdf():
    with tempfile.TemporaryDirectory() as d:
        path = _make_pdf(Path(d) / "test.pdf", letter, 5)
        result = validate_pdf_structure(path)
        assert result.valid
        assert result.page_count == 5
        assert result.width_pts is not None


def test_validate_structure_missing_file():
    result = validate_pdf_structure(Path("/nonexistent/file.pdf"))
    assert not result.valid
    assert "not found" in result.errors[0].lower()


def test_validate_structure_not_a_pdf():
    with tempfile.TemporaryDirectory() as d:
        path = Path(d) / "fake.pdf"
        path.write_text("this is not a pdf")
        result = validate_pdf_structure(path)
        assert not result.valid
        assert "not a valid pdf" in result.errors[0].lower()


def test_validate_interior_correct_dimensions():
    with tempfile.TemporaryDirectory() as d:
        page_size = trim_size_pts("6x9")
        path = _make_pdf(Path(d) / "interior.pdf", page_size, 120)
        result = validate_interior(path, "6x9", 120)
        assert result.valid
        assert result.page_count == 120


def test_validate_interior_wrong_dimensions():
    with tempfile.TemporaryDirectory() as d:
        path = _make_pdf(Path(d) / "interior.pdf", letter, 120)
        result = validate_interior(path, "6x9", 120)
        assert not result.valid
        assert any("mismatch" in e.lower() for e in result.errors)


def test_validate_interior_page_count_mismatch():
    with tempfile.TemporaryDirectory() as d:
        page_size = trim_size_pts("6x9")
        path = _make_pdf(Path(d) / "interior.pdf", page_size, 100)
        result = validate_interior(path, "6x9", 120)
        # Page count mismatch is a warning, not an error
        assert result.valid
        assert any("mismatch" in w.lower() for w in result.warnings)


def test_validate_interior_too_few_pages():
    with tempfile.TemporaryDirectory() as d:
        page_size = trim_size_pts("6x9")
        path = _make_pdf(Path(d) / "interior.pdf", page_size, 10)
        result = validate_interior(path, "6x9", 10)
        assert not result.valid
        assert any("too few" in e.lower() for e in result.errors)


def test_validate_cover_generated():
    """Validate a cover PDF generated by CoverGenerator."""
    gen = CoverGenerator()
    with tempfile.TemporaryDirectory() as d:
        cover_path = gen.generate(
            title="Test Book",
            trim_size="6x9",
            page_count=120,
            output_path=Path(d) / "cover.pdf",
        )
        result = validate_cover(cover_path, "6x9", 120)
        assert result.valid, f"Cover validation failed: {result.errors}"
        assert result.page_count == 1
